config/routes.rb
BostonRuby::Application.routes.draw do
  %w{jobs projects users companies}.each do |dead_route|
    match "/#{dead_route}" => redirect('/')
  end

  root :to => 'high_voltage/pages#show', :id => 'home'
  get '/calendar' => 'high_voltage/pages#show', :id => 'calendar', :as => 'calendar'
  resources :proposals, :only => [:new, :create]
  get '/presentations/month/:month/' => 'presentations#index', :as => 'month_presentations'
  get '/presentations/upcoming' => 'presentations#index', :as => 'upcoming_presentations', :defaults => { :upcoming => true }
  resources :presentations, :only => [:index, :show]
  get '/presenters/leaders' => 'leader_board#index'
  resources :presenters, :only => [:show]
  get '/project_night' => 'high_voltage/pages#show', :id => 'project_night', :as => 'project_night'


  namespace 'admin' do
    resources 'presentations' do
      collection do
        get "month/:month" => :index, :as => "month"
      end
    end
    resources 'blogs'
    resources :events, :only => [:show, :new, :create, :edit, :update]
    resources :locations, :only => [:new, :create, :edit, :destroy]
    resources :event_types, :only => [:new, :create]
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :name
  validates_presence_of :name
  attr_accessible :street
  validates_presence_of :street
  attr_accessible :city
  validates_presence_of :city
  attr_accessible :state
  validates_presence_of :state
  attr_accessible :zipcode
  validates_presence_of :zipcode
  attr_accessible :time_of_deletion

  has_many :events,
    inverse_of: :location

  def self.available
    where(:time_of_deletion => nil)
  end
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < AdminController
  before_filter :check_for_organizer

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(params[:location])

    if @location.save
      flash[:notice] = 'Created location successfully'
      redirect_to new_admin_location_path
    else
      flash[:notice] = 'Invalid information. Please try again'
      render :new
    end
  end

  def edit
    @location = Location.find(params[:id])
  end

  def destroy
    @location = Location.find(params[:id])
    @location.time_of_deletion = Time.now

    if @location.save
      flash[:notice] = 'Successful deletion'
      redirect_to new_admin_location_path
    end
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def new
    @location = Location.new
  end

  def create
    @location = Location.new(params[:location])

    if @location.save
      flash[:notice] = 'Created location successfully'
      redirect_to new_location_path
    else
      flash[:notice] = 'Invalid information. Please try again'
      render :new
    end
  end

  def edit
    @location = Location.find(params[:id])
  end

  def destroy
    @location = Location.find(params[:id])
    @location.time_of_deletion = Time.now

    if @location.save
      redirect_to new_location_path
    end
  end
end

app/views/admin/locations/_form.html.erb
<%= simple_form_for admin_location_path do |form| %>
  <%= form.input :name %>
  <%= form.input :street %>
  <%= form.input :suite_address %>
  <%= form.input :city %>
  <%= form.input :state %>
  <%= form.input :zipcode %>

  <%= form.submit 'Submit' %>

<% end %>

app/views/admin/locations/edit.html.erb
<h1> Edit Location </h1>

<%= render 'form' %>

<%= link_to "Remove location", admin_location_path(@location), :data => { :confirm => 'Are you sure?' }, :method => :delete %>

app/views/admin/locations/new.html.erb
<%= simple_form_for [:admin, @location], :validate => true do |form| %>
  <%= form.input :name %>
  <%= form.input :street %>
  <%= form.input :suite_address %>
  <%= form.input :city %>
  <%= form.input :state %>
  <%= form.input :zipcode %>
  <%= form.submit 'Submit' %>
<% end %>