config/routes.rb
BostonRuby::Application.routes.draw do
  %w{jobs projects users companies}.each do |dead_route|
    match "/#{dead_route}" => redirect('/')
  end

  root :to => 'high_voltage/pages#show', :id => 'home'
  get '/calendar' => 'high_voltage/pages#show', :id => 'calendar', :as => 'calendar'
  resources :proposals, :only => [:new, :create]
  get '/presentations/month/:month/' => 'presentations#index', :as => 'month_presentations'
  get '/presentations/upcoming' => 'presentations#index', :as => 'upcoming_presentations', :defaults => { :upcoming => true }
  resources :presentations, :only => [:index, :show]
  get '/presenters/leaders' => 'leader_board#index'
  resources :presenters, :only => [:show]
  get '/project_night' => 'high_voltage/pages#show', :id => 'project_night', :as => 'project_night'


  namespace 'admin' do
    resources 'presentations' do
      collection do
        get "month/:month" => :index, :as => "month"
      end
    end
    resources 'blogs'
    resources :events, :only => [:show, :new, :create, :edit, :update]
    resources :locations, :only => [:new, :create, :edit, :destroy]
    resources :event_types, :only => [:new, :create]
  end
end

app/views/shared/_flashes.html.erb
<div id="flash">
  <% flash.each do |key, value| -%>
    <div id="flash_<%= key %>"><%= value %></div>
  <% end -%>
</div>

app/views/shared/_ga.html.erb
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-23942957-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

app/views/shared/_nav.html.erb
<nav class='links'>
<ul>
  <li><%= link_to_unless_current_with_span "Presentations", presentations_path %></li>
  <li><%= link_to_unless_current_with_span "Project Night", project_night_path %></li>
  <li><%= link_to_unless_current_with_span "Submit Proposal", "https://www.papercall.io/bostonrb" %></li>

  <li><a href="http://twitter.com/bostonrb" title="Tweets from bostonrb">Twitter</a></li>
  <li><a href="http://github.com/bostonrb" title="Shared code from bostonrb">Github</a></li>
  <li><a href="https://www.meetup.com/bostonrb/messages/boards/forum/29446267" title="Opportunities for Boston Rubyists">Jobs</a></li>
</ul>
</nav>